# Path to data
path: "dicom/dicom2/ScalarVolume_14/"



# crop image
xmin: 240
xmax: 262
ymin: 145
ymax: 108

# select frames
first_frame: 287
last_frame: 298

# select color threshold
threshold: -50

